#!/bin/bash

# Establecer el directorio de trabajo
DIR="$(dirname "$(readlink -f "${0}")")"

# Establecer variables de entorno necesarias
export PATH="$DIR/usr/bin:$PATH"
export LD_LIBRARY_PATH="$DIR/usr/lib:$LD_LIBRARY_PATH"

# Comprobar si el ejecutable existe
if [ ! -x "$DIR/downloader-site" ]; then
    echo "Error: El ejecutable 'downloader-site' no se encuentra o no es ejecutable."
    exit 1
fi

# Ejecutar la aplicación
exec "$DIR/downloader-site" "$@"
